### ISSUE TITLE
typescript support

### ISSUE THREAD

**Issue by Egzscure** [stevekanger/react-superstore#1]
Getting "Object literal may only specify known properties, and 'type' does not exist in type" error when trying to dispatch actions from typescript.

this is a very useful way to manage the state, just wish it could support ts.

my workaround to make it work with TS if anyone needs.
create an interface like this:

interface IStore{
  type:any;
  payload:any;
}

save createStore as .ts, add :any where it is giving errors and:
 const listeners = new Set()
replace with
 const listeners = new Set< any >()

and replace
const useStore = (mapState = (store) => store) => {

with
const useStore = (mapState = (store:IStore) => store) => {

**Comment by SteveKanger** [comment]
I just posted this as a reference because it is a simple concept of state management and I really didn't want to turn it into an npm package because maintaining them is kind of a nightmare. So I just provided the script and people can modify it to their liking. Here is a quick typescript example if you are interested. 

Note: I havent really tested this much and just went over it real quick but here it goes.

```
import { useState, useEffect, useLayoutEffect } from "react";

type Store = any;
type Reducer = (store: Store, action: any) => void;
type Listener = {
  mapState: (store: any) => any;
  updater: React.Dispatch<React.SetStateAction<any>>;
  state: any;
};
type CreateStoreReturn = [
  (store?: Store) => any,
  (action: any) => void,
  () => Store
];

const effect = typeof window === "undefined" ? useEffect : useLayoutEffect;
const isFn = (fn: () => any) => typeof fn === "function";
const isObj = (obj: {}) =>
  typeof obj === "object" &&
  typeof obj !== "function" &&
  !Array.isArray(obj) &&
  obj !== null;

const shouldUpdate = (state: any, newState: any) => {
  if (state === newState) return false;

  if (isObj(state) && isObj(newState)) {
    for (let key in newState) {
      if (state[key] !== newState[key]) return true;
    }
    return false;
  }

  return true;
};

const createStore = (
  initialStore: Store,
  reducer?: Reducer
): CreateStoreReturn => {
  let store: Store = initialStore;
  const listeners = new Set<Listener>();

  const getStore = () => store;

  const dispatch = (action: any) => {
    if (reducer) {
      store = reducer(store, action);
    } else {
      store = isFn(action) ? action(store) : action;
    }

    listeners.forEach(({ state, mapState, updater }) => {
      const newState = mapState(store);
      if (shouldUpdate(state, newState)) updater(() => newState);
    });
  };

  const useStore = (mapState = (store: Store) => store) => {
    const [, updater] = useState();
    const state = mapState(store);

    effect(() => {
      const listener = {
        updater,
        state,
        mapState
      };

      listeners.add(listener);
      return () => {
        listeners.delete(listener);
      };
    }, [state, mapState]);

    return state;
  };

  return [useStore, dispatch, getStore];
};

export default createStore;
```

if you see anything I may have missed let me know. I may post a typescript version of this as well. But I can't believe this pattern is more widely talked about in state management for react. I don't really have any ambitions to maintain an npm package because at its core the principal is really simple. Just return a react hook from the createStore function and pass the React.setState function to a listener pattern when the component mounts. Then you can fire the setState whenever you set the store.

**Comment by stevekanger** [comment]
Npm package has been created with typescript support. [react-gsh npm package](https://www.npmjs.com/package/react-gsh)
